from __future__ import annotations

import ast
import json
import re
import subprocess
from pathlib import Path

import yaml


PRIVATE_LOCAL_DATA_FILES = {
    "data/evaluation/coreguapa_identified_all.jsonl",
}


class LmEvalTaskLoader(yaml.SafeLoader):
    pass


LmEvalTaskLoader.add_constructor(
    "!function", lambda loader, node: loader.construct_scalar(node)
)


def tracked_files() -> list[Path]:
    output = subprocess.check_output(["git", "ls-files"], text=True)
    return [Path(line) for line in output.splitlines()]


def load_yaml(path: Path) -> object:
    loader = LmEvalTaskLoader if path.parts[:2] == ("evaluation", "lm_eval_tasks") else yaml.SafeLoader
    with path.open("r", encoding="utf-8") as handle:
        return yaml.load(handle, Loader=loader)


def iter_data_files(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        paths: list[str] = []
        for item in value:
            paths.extend(iter_data_files(item))
        return paths
    if isinstance(value, dict):
        paths: list[str] = []
        for item in value.values():
            paths.extend(iter_data_files(item))
        return paths
    return []


def test_tracked_python_json_and_yaml_parse() -> None:
    for path in tracked_files():
        if path.suffix == ".py":
            ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        elif path.suffix == ".json":
            json.loads(path.read_text(encoding="utf-8"))
        elif path.suffix in {".yaml", ".yml"}:
            load_yaml(path)


def test_matrices_have_required_top_level_sections() -> None:
    for path in Path("configs/train").glob("*_cpt_matrix.y*ml"):
        matrix = load_yaml(path)
        assert isinstance(matrix, dict)
        for key in ("generated_config_dir", "runs_root", "reporting", "model", "defaults", "profiles"):
            assert key in matrix, f"{path} is missing {key}"

    for path in Path("configs/evaluation").glob("*_eval_matrix.y*ml"):
        matrix = load_yaml(path)
        assert isinstance(matrix, dict)
        for key in (
            "generated_config_dir",
            "outputs_root",
            "task_include_path",
            "training_outputs_root",
            "model",
            "defaults",
            "suites",
            "profiles",
        ):
            assert key in matrix, f"{path} is missing {key}"


def test_local_json_tasks_reference_available_or_private_files() -> None:
    missing: set[str] = set()
    for path in Path("evaluation/lm_eval_tasks").glob("*.yaml"):
        task_config = load_yaml(path)
        assert isinstance(task_config, dict)
        if task_config.get("dataset_path") != "json":
            continue

        dataset_kwargs = task_config.get("dataset_kwargs", {})
        assert isinstance(dataset_kwargs, dict)
        for data_file in iter_data_files(dataset_kwargs.get("data_files")):
            if not Path(data_file).exists():
                missing.add(data_file)

    assert missing <= PRIVATE_LOCAL_DATA_FILES


def test_dependency_inputs_pin_upstream_framework_commits() -> None:
    requirements = Path("requirements.in").read_text(encoding="utf-8")
    for repository in (
        "hiyouga/LlamaFactory",
        "EleutherAI/lm-evaluation-harness",
    ):
        match = re.search(rf"{re.escape(repository)}\.git@([0-9a-f]+)", requirements)
        assert match is not None, f"{repository} is not pinned in requirements.in"
        assert len(match.group(1)) == 40, f"{repository} must use a full commit SHA"


def test_generated_locks_exclude_platform_specific_pytorch_packages() -> None:
    for path in (Path("requirements.txt"), Path("requirements-dev.txt")):
        contents = path.read_text(encoding="utf-8")
        assert "This file is autogenerated by pip-compile" in contents
        for package in ("torch", "torchaudio", "torchvision"):
            assert not re.search(rf"^{package}==", contents, flags=re.MULTILINE)

    gpu_requirements = Path("requirements-gpu-cu128.txt").read_text(encoding="utf-8")
    for package in ("torch", "torchaudio", "torchvision"):
        assert re.search(rf"^{package}==", gpu_requirements, flags=re.MULTILINE)


def test_ci_dependencies_remain_lightweight() -> None:
    ci_requirements = Path("requirements-ci.txt").read_text(encoding="utf-8").lower()
    for package in ("torch", "transformers", "llamafactory", "lm_eval"):
        assert package not in ci_requirements


def test_readme_uses_pinned_pip_installation() -> None:
    readme = Path("README.md").read_text(encoding="utf-8")
    assert "python -m pip install -r requirements.txt" in readme
    assert "git clone --depth 1" not in readme


def test_public_command_references_match_current_entry_points() -> None:
    data_readme = Path("data/README.md").read_text(encoding="utf-8")
    pipeline_script = Path("scripts/run_pipeline.sh").read_text(encoding="utf-8")

    assert "python -m src.generate_train_configs --model gemma4_12b --overwrite" in data_readme
    assert "generate_train_configs --matrix" not in data_readme
    assert "scripts/run_pipeline.sh" in pipeline_script
    assert "scripts/run_cpt.sh" not in pipeline_script
