#!/usr/bin/env python3
"""Generate LLaMA Factory CPT training configs from an experiment matrix."""

from __future__ import annotations

import click
import os
import yaml

from typing import Any


def load_yaml(path: str) -> dict[str, Any]:
    """Load a YAML file as a dictionary.

    Args:
        path: YAML file path.

    Returns:
        Parsed YAML dictionary.

    Raises:
        ValueError: If the YAML file does not contain a mapping.
    """
    with open(path, 'r', encoding='utf-8') as handle:
        data = yaml.safe_load(handle)

    if not isinstance(data, dict):
        raise ValueError(f'YAML file must contain a mapping: {path}')

    return data


def require_mapping(data: dict[str, Any], key: str) -> dict[str, Any]:
    """Read a required mapping from a dictionary.

    Args:
        data: Dictionary to inspect.
        key: Required mapping key.

    Returns:
        Mapping value.

    Raises:
        ValueError: If the key is missing or is not a mapping.
    """
    value = data.get(key)
    if not isinstance(value, dict):
        raise ValueError(f'Matrix key must be a mapping: {key}')

    return value


def merge_dicts(*items: dict[str, Any]) -> dict[str, Any]:
    """Merge dictionaries left to right, skipping None values.

    Args:
        items: Dictionaries to merge.

    Returns:
        Merged dictionary.
    """
    merged = {}
    for item in items:
        for key, value in item.items():
            if value is not None:
                merged[key] = value

    return merged


def write_yaml(path: str, data: dict[str, Any], overwrite: bool) -> None:
    """Write one YAML file.

    Args:
        path: Destination YAML path.
        data: Data to serialize.
        overwrite: Whether an existing file can be replaced.

    Returns:
        None.

    Raises:
        FileExistsError: If the file exists and overwrite is false.
    """
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(f'Refusing to overwrite existing config: {path}')

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        yaml.safe_dump(data, handle, sort_keys=False, allow_unicode=True)


def shell_quote(value: Any) -> str:
    """Quote a value for POSIX shell env files.

    Args:
        value: Value to quote.

    Returns:
        Single-quoted shell string.
    """
    escaped = str(value).replace('\'', '\'\"\'\"\'')
    return f'\'{escaped}\''


def write_wandb_env(
    output_dir: str, reporting: dict[str, Any], model_key: str, overwrite: bool
) -> str:
    """Write W&B environment defaults from matrix reporting settings.

    Args:
        output_dir: Generated config output directory.
        reporting: Matrix reporting settings.
        model_key: Short model identifier used as the default W&B run group.
        overwrite: Whether an existing env file can be replaced.

    Returns:
        Path to the written env file.
    """
    path = os.path.join(output_dir, model_key, 'wandb.env')
    if os.path.exists(path) and not overwrite:
        raise FileExistsError(f'Refusing to overwrite existing env file: {path}')

    os.makedirs(os.path.dirname(path), exist_ok=True)
    env_values = {
        'WANDB_PROJECT': reporting.get('wandb_project'),
        'WANDB_RUN_GROUP': reporting.get('wandb_run_group', model_key),
        'WANDB_MODE': reporting.get('wandb_mode'),
        'WANDB_DIR': reporting.get('wandb_dir', 'wandb'),
        'WANDB_TAGS': reporting.get('wandb_tags'),
    }
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write('# Generated by src.generate_train_configs. Do not edit by hand.\n')
        for key, value in env_values.items():
            if value is not None:
                handle.write(f'export {key}={shell_quote(value)}\n')

    return path


def run_name(model_key: str, method: str, corpus: str, rank: int | None) -> str:
    """Build a stable run name.

    Args:
        model_key: Short model identifier.
        method: Fine-tuning method name.
        corpus: Dataset configuration name.
        rank: Optional LoRA rank.

    Returns:
        Stable run name used for YAML filenames and output directories.
    """
    if method == 'lora':
        if rank is None:
            raise ValueError('LoRA runs require a rank.')
        return f'{model_key}_lora_r{rank}_{corpus}'

    return f'{model_key}_{method}_{corpus}'


def output_dir_for_run(
    runs_root: str,
    profile_name: str,
    method: str,
    corpus: str,
    name: str,
    rank: int | None,
) -> str:
    """Build the model output directory for one run.

    Args:
        runs_root: Root output directory for all training runs.
        profile_name: Profile name, such as smoke or experiments.
        method: Fine-tuning method name.
        corpus: Dataset configuration name.
        name: Stable run name.
        rank: Optional LoRA rank.

    Returns:
        Output directory path.
    """
    if method == 'lora':
        return os.path.join(runs_root, profile_name, method, f'rank_{rank}', corpus)

    return os.path.join(runs_root, profile_name, method, corpus, name)


def model_training_defaults(model: dict[str, Any]) -> dict[str, Any]:
    """Build training defaults controlled by the model definition.

    Args:
        model: Matrix model definition.

    Returns:
        Training defaults derived from model-level settings.
    """
    return {
        'cutoff_len': model.get('cutoff_len'),
    }


def training_config(
    matrix: dict[str, Any],
    profile_name: str,
    method: str,
    corpus: str,
    rank: int | None,
) -> dict[str, Any]:
    """Build one LLaMA Factory training config.

    Args:
        matrix: Loaded experiment matrix.
        profile_name: Profile being generated.
        method: Fine-tuning method name.
        corpus: Dataset configuration name.
        rank: Optional LoRA rank.

    Returns:
        LLaMA Factory training config dictionary.
    """
    model = require_mapping(matrix, 'model')
    defaults = require_mapping(matrix, 'defaults')
    common = require_mapping(defaults, 'common')
    method_defaults = require_mapping(defaults, method)
    profiles = require_mapping(matrix, 'profiles')
    profile = require_mapping(profiles, profile_name)
    profile_overrides = profile.get('overrides', {})
    if not isinstance(profile_overrides, dict):
        raise ValueError(f'Profile overrides must be a mapping: {profile_name}')

    model_key = model['key']
    name = run_name(model_key, method, corpus, rank)
    config = merge_dicts(
        {
            'model_name_or_path': model['model_name_or_path'],
            'model_revision': model.get('model_revision', 'main'),
            'trust_remote_code': bool(model.get('trust_remote_code', True)),
        },
        common,
        model_training_defaults(model),
        method_defaults,
        profile_overrides,
        {
            'dataset': corpus,
            'output_dir': output_dir_for_run(
                matrix['runs_root'], profile_name, method, corpus, name, rank
            ),
            'run_name': name,
        },
    )

    if method == 'lora':
        if rank is None:
            raise ValueError('LoRA runs require a rank.')
        alpha_multiplier = int(method_defaults.get('lora_alpha_multiplier', 2))
        config['lora_rank'] = rank
        config['lora_alpha'] = rank * alpha_multiplier
        config.pop('lora_alpha_multiplier', None)

    if config.get('do_eval') and 'eval_dataset' not in config:
        config['eval_dataset'] = f'{corpus}_validation'

    if 'cutoff_len' not in config:
        raise ValueError(
            f'Missing cutoff_len for {method} run. Set model.cutoff_len or '
            f'defaults.{method}.cutoff_len in the matrix.'
        )

    return config


def iter_runs(matrix: dict[str, Any], profile_name: str):
    """Yield training run coordinates for a profile.

    Args:
        matrix: Loaded experiment matrix.
        profile_name: Profile to generate.

    Returns:
        Iterator over method, corpus, rank tuples.
    """
    profiles = require_mapping(matrix, 'profiles')
    profile = require_mapping(profiles, profile_name)
    corpora = profile['corpora']
    methods = profile['methods']
    ranks = profile.get('lora_ranks', [])

    for method in methods:
        if method == 'lora':
            for rank in ranks:
                for corpus in corpora:
                    yield method, corpus, int(rank)
        else:
            for corpus in corpora:
                yield method, corpus, None


def generated_config_path(
    output_dir: str, profile_name: str, model_key: str, name: str
) -> str:
    """Build the generated training config path.

    Args:
        output_dir: Generated config root directory.
        profile_name: Profile being generated.
        model_key: Short model identifier.
        name: Generated config filename stem.

    Returns:
        Model-scoped generated config path.
    """
    return os.path.join(output_dir, profile_name, model_key, f'{name}.yaml')


@click.command(
    context_settings={'show_default': True},
    help='Generate LLaMA Factory YAML configs from a CPT experiment matrix.',
)
@click.option(
    '--matrix',
    'matrix_path',
    type=click.Path(exists=True, dir_okay=False),
    required=True,
    help='Training matrix YAML file.',
)
@click.option(
    '--profile',
    'profile_names',
    multiple=True,
    help='Profile to generate. Repeat to generate multiple profiles. Defaults to all profiles.',
)
@click.option('--overwrite', is_flag=True, help='Overwrite generated YAML files.')
def main(matrix_path: str, profile_names: tuple[str, ...], overwrite: bool) -> None:
    """Generate LLaMA Factory training YAML files.

    Args:
        matrix_path: Training matrix YAML file.
        profile_names: Profile names to generate.
        overwrite: Whether existing generated YAML files can be replaced.

    Returns:
        None.
    """
    matrix = load_yaml(matrix_path)
    profiles = require_mapping(matrix, 'profiles')
    selected_profiles = profile_names or tuple(profiles.keys())
    output_dir = matrix.get('generated_config_dir', 'configs/train/generated')
    reporting = require_mapping(matrix, 'reporting')
    env_path = write_wandb_env(output_dir, reporting, matrix['model']['key'], overwrite)
    written = 0

    print(env_path)
    for profile_name in selected_profiles:
        if profile_name not in profiles:
            raise ValueError(f'Unknown profile: {profile_name}')

        for method, corpus, rank in iter_runs(matrix, profile_name):
            name = run_name(matrix['model']['key'], method, corpus, rank)
            path = generated_config_path(output_dir, profile_name, matrix['model']['key'], name)
            config = training_config(matrix, profile_name, method, corpus, rank)
            write_yaml(path, config, overwrite)
            print(path)
            written += 1

    print(f'[done] wrote {written} config files')


if __name__ == '__main__':
    main()
